### PR TITLE
Rebuild for libprotobuf 5.27.5

### PR DESCRIPTION
**Pull request by h-vetinari**

### CODE REVIEW

**Comment by h-vetinari** [comment]
Well, this gridlock is just getting more and more fun. 😑

**Comment by h-vetinari** [comment]
I hadn't commented the details at the time, but protobuf did a major version bump for the java bindings from 3.25 to 4.26. And grpc-java still isn't (fully?) compatible yet: https://github.com/grpc/grpc-java/issues/11015

**Comment by xhochy** [comment]
I found the issue. Let me push it in 2-3h when I'm at my laptop again

**Comment by h-vetinari** [comment]
That's great news! I'm removing the debug commits and you can then build on top.

**Comment by xhochy** [comment]
No, it's not on this feedstock 🤣

**Comment by h-vetinari** [comment]
FWIW, arrow also seems to be missing some protobuf symbols on windows. Haven't looked in more detail yet

**Pull request closed without merging**
